version: "3"

services:
  factorio:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: factorio_experimental
    restart: unless-stopped
    volumes:
      - ./saves:/opt/factorio/saves
    ports:
      - 34197:34197/udp
    env_file: env
    #stop_grace_period: 5m
  namecheap-ddns:
    image: joshuamorris3/namecheap-ddns-update
    container_name: factorio_namecheap_ddns_updater
    restart: unless-stopped
    env_file: env
